server:
  port: ${PORT:8081}

messages:
  home1: Hello, Memor!
home2: Hello, Memor
home3: Hello,Memor:),3,g
home4: 2
 

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: SYSTEM
    password: 000000
    driver-class-name: oracle.jdbc.OracleDriver
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    servlet:
       content-type: text/html
    